# Model arguments
model_name_or_path: "/mnt/vdb/huggingface/hub/models--Qwen--Qwen2.5-3B-Instruct/snapshots/aa8e72537993ba99e69dfaafa59ed015b17504d1"
torch_dtype: float16
# attn_implementation: flash_attention_2
bf16: false
tf32: false
output_dir: models/test_grpo_big # grpo-smolLM2-360m-halfcheetah-expert-3-v1

# Dataset arguments
dataset_id_or_path: "/mnt/vdb/abenechehab/rlft4rl/data/sft/mujoco_halfcheetah_expert-v0_10_sp0_ct0.json"
eval_dataset_id_or_path: ""  # "/mnt/vdb/abenechehab/rlft4rl/data/sft/mujoco_halfcheetah_expert-v0_3_sp0.json"
dataset_size: 10000

# Lora Arguments
use_peft: true
load_in_4bit: false
lora_target_modules: "all-linear"
# important as we need to train the special tokens for the chat template of llama
lora_modules_to_save: ["lm_head", "embed_tokens"] # you might need to change this for qwen or other models
lora_r: 8
lora_alpha: 8

# Training arguments
max_steps: 10
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-7 # 1.0e-6 as in the deepseek math paper 5-e7 from https://hijkzzz.notion.site/unraveling-rlhf-and-its-variants-engineering-insights#147d9a33ecc9806090f3d5c749d31f05
lr_scheduler_type: cosine
warmup_ratio: 0.03

# ######## GRPO specific parameters ########
beta: 0.001 # 0.04 as in the deepseek math paper 0.001 from https://hijkzzz.notion.site/unraveling-rlhf-and-its-variants-engineering-insights#147d9a33ecc9806090f3d5c749d31f05
max_prompt_length: 1024
max_completion_length: 100
num_generations: 4
use_vllm: true
# vllm_device: "cuda:7"
vllm_num_processes: 2
vllm_gpu_memory_utilization: 0.9
vllm_dtype: "half"
############################################

# Logging arguments
logging_strategy: steps
logging_steps: 2
report_to:
- tensorboard
save_strategy: "steps"
save_steps: 25
seed: 42

# Hugging Face Hub
push_to_hub: false
  # hub_model_id: llama-3-1-8b-math-orca-qlora-10k-ep1 # if not defined same as output_dir
hub_strategy: every_save
