# Script arg
reward_model_path: "models/reward_models/halfcheetah_medium/rw_medium.pt"

# Model arguments
model_name_or_path: "Qwen/Qwen3-4B"  # "models/sft_smollm2_1.7b_halfcheetah_expert-v0_100_sp0_ct0_full/final_model"  # "HuggingFaceTB/SmolLM2-1.7B-Instruct" # "models/sft_gemma_3_1b_halfcheetah_medium_400kep_v5/final_model" # "Qwen/Qwen2.5-0.5B-Instruct" # "google/gemma-3-1b-it" 
# model_name_or_path: "models/sft_gemma-3-1b_halfcheetah_medium_1000ep/final_model"
# torch_dtype: bfloat16
attn_implementation: flash_attention_2
bf16: true
tf32: true
output_dir: "models/grpo-full_qwen3_4b_hc_m_1Mep_v7_format+BC"  # "models/grpo_qwen-2-5-1-5b_halfcheetah_medium_1000ep_v6"  # "models/grpo_sft_smollm2_1.7b_halfcheetah_expert-v0_100_sp0_ct0_full"

# Dataset arguments
dataset_id_or_path: "data/sft/mujoco_halfcheetah_medium-v0_1000_sp0_ct0.json"
dataset_size: 1000000

# Lora Arguments
use_peft: false
load_in_4bit: false
lora_target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]  # "all-linear" 
# important as we need to train the special tokens for the chat template of llama
# lora_modules_to_save: ["lm_head", ] # you might need to change this for qwen or other models # "embed_tokens"
lora_r: 128
lora_alpha: 512
# lora_dropout: 0.05

# ######### Training arguments ##########
max_steps: 1000
per_device_train_batch_size: 8
gradient_accumulation_steps: 4
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1.0e-6 # 5.0e-7 # 1.0e-6 as in the deepseek math paper 5-e7 from https://hijkzzz.notion.site/unraveling-rlhf-and-its-variants-engineering-insights#147d9a33ecc9806090f3d5c749d31f05
lr_scheduler_type: cosine
warmup_ratio: 0.03
log_completions: true
num_completions_to_print: 1
num_train_epochs: 10
########################

# ######## GRPO specific parameters ########
beta: 0.04  # 0.001 # 0.04 as in the deepseek math paper 0.001 from https://hijkzzz.notion.site/unraveling-rlhf-and-its-variants-engineering-insights#147d9a33ecc9806090f3d5c749d31f05
max_prompt_length: 512
max_completion_length: 100
num_generations: 4
scale_rewards: false
################################################


# ######## vLLM ########
use_vllm: false
vllm_device: "cuda:0"
vllm_num_processes: 1
vllm_gpu_memory_utilization: 0.5
# vllm_dtype: "half"
########################

# ######## Logging arguments ########
logging_strategy: steps
logging_steps: 2
report_to:
- tensorboard
save_strategy: "steps"
save_steps: 100
seed: 42

# Hugging Face Hub
push_to_hub: false
  # hub_model_id: llama-3-1-8b-math-orca-qlora-10k-ep1 # if not defined same as output_dir
hub_strategy: every_save
################################################
