# Model arguments
model_name_or_path: "/mnt/vdb/huggingface/hub/models--meta-llama--Llama-3.2-1B-Instruct/snapshots/9213176726f574b556790deb65791e0c5aa438b6"
torch_dtype: bfloat16
# attn_implementation: flash_attention_2
bf16: true
tf32: false
output_dir: "models/llama-3-2-1B-halfcheetah-expert-1ep-50-sp0-v3"

# Dataset arguments
dataset_id_or_path: "/mnt/vdb/abenechehab/rlft4rl/data/sft/mujoco_halfcheetah_expert-v0_50_sp0.json"
eval_dataset_id_or_path: "/mnt/vdb/abenechehab/rlft4rl/data/sft/mujoco_halfcheetah_expert-v0_3_sp0.json"
dataset_size: 50000
max_seq_length: 200
packing: false
dataset_kwargs:
  add_special_tokens: false
  append_concat_token: false

# LoRA arguments
use_peft: true
load_in_4bit: true
lora_target_modules: "all-linear"
# important as we need to train the special tokens for the chat template of llama
lora_modules_to_save: ["lm_head", "embed_tokens"] # you might need to change this for qwen or other models
lora_r: 16
lora_alpha: 16

# Training arguments
num_train_epochs: 1
per_device_train_batch_size: 24
gradient_accumulation_steps: 2
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 2.0e-4
lr_scheduler_type: constant
warmup_ratio: 0.1
# custom
do_eval: true
evaluation_strategy: "steps"
metric_for_best_model: "eval_loss"
load_best_model_at_end: true

# Logging arguments
logging_strategy: "steps"
logging_steps: 5
report_to:
- tensorboard
save_strategy: "steps"
seed: 42

# Hugging Face Hub
push_to_hub: false
# hub_model_id: llama-3-1-8b-math-orca-qlora-10k-ep1 # if not defined same as output_dir
hub_strategy: every_save
