# Model arguments
model_name_or_path: "/mnt/vdb/huggingface/hub/models--HuggingFaceTB--SmolLM2-360M-Instruct/snapshots/29ba36fc600930f3cfe6e1a93ab43af299542dc4"
torch_dtype: float16
# attn_implementation: flash_attention_2
bf16: true
tf32: false
output_dir: models/smolLM2-360m-halfcheetah-expert

# Dataset arguments
dataset_id_or_path: "/mnt/vdb/abenechehab/rlft4rl/data/sft/mujoco_halfcheetah_expert-v0_20.json"
dataset_size: 20000
max_seq_length: 512
packing: false
dataset_kwargs:
  add_special_tokens: false
  append_concat_token: false

# LoRA arguments
use_peft: true
load_in_4bit: true
lora_target_modules: "all-linear"
# important as we need to train the special tokens for the chat template of llama
lora_modules_to_save: ["lm_head", "embed_tokens"] # you might need to change this for qwen or other models
lora_r: 16
lora_alpha: 16

# Training arguments
num_train_epochs: 10
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 2.0e-4
lr_scheduler_type: constant
warmup_ratio: 0.1

# Logging arguments
logging_strategy: steps
logging_steps: 5
report_to:
- tensorboard
save_strategy: "epoch"
seed: 42

# Hugging Face Hub
push_to_hub: false
# hub_model_id: llama-3-1-8b-math-orca-qlora-10k-ep1 # if not defined same as output_dir
hub_strategy: every_save
